### ISSUE TITLE
[Question] What is the diffrence of this with Mozilla's?

### ISSUE THREAD

**Issue by umitseyhan75** [mrdrogdrog/twemoji-color-font#2]
What is the difference between this project and [Mozilla's Twemoji colr](https://github.com/mozilla/twemoji-colr)? They both seem like the same thing.

**Comment by mrdrogdrog** [comment]
The Mozilla repository contains the source code of the converter to process the SVGs and generate the font files. This repository contains the actual compiled files that are also included in the npm package. I use twemoji-colr (actually my own fork) to build the files and then archive them here.

I also plan to rebuild the code of twemoji-colr here later using only one language and much testing.

**Comment by umitseyhan75** [comment]
> The Mozilla repository contains the source code of the converter to process the SVGs and generate the font files.

But they also provide compiled assets under [releases](https://github.com/mozilla/twemoji-colr/releases/).

**Comment by mrdrogdrog** [comment]
Not as npm package (my npm package is linked to this repository because I plan to remove the compiled files form the git as soon as the rewrite is done), not always with the newest release of twemoji and not as woff2.

**Comment by mrdrogdrog** [comment]
Also I've switched to a fork of twemoji because the official Twitter repository seems to be dead.

**Comment by umitseyhan75** [comment]
Thank you for the answers.
